defaults:
  - recflow.yaml
  - _self_

name: alphaflow
target: src.training.loss.AlphaFlowLoss

adaptive_loss_weight_eps: 0.001

time_sampling_fm: # Distribution when t_next == t
  timestep_distrib_type: logit_norm
  scale: 1.0
  location: -0.4
  eps: 0

distrib_t_t_next_mf: # Distribution of t_next and t when t_next != t
  type: minmax
  time_sampling_mf_t:
    timestep_distrib_type: logit_norm
    scale: 1.0
    location: -0.4
    eps: 0
  time_sampling_mf_t_next:
    timestep_distrib_type: logit_norm
    scale: 1.0
    location: -0.4
    eps: 0

ratio_fm: # Schedule for % t_next == t
  scheduler: constant
  initial_value: 0.75
  end_value: 0.75
  change_init_steps: 0
  change_end_steps: 0
  gamma: 1.0
  clamp_value: 0.0
  up_clamp_value: ~

alpha: # Schedule for alpha
  scheduler: constant
  initial_value: 0.0
  end_value: 0.0
  change_init_steps: 0
  change_end_steps: 0
  gamma: 1.0
  clamp_value: 0.0
  discrete_training: false
  up_clamp_value: ~

cfg_params: # Cfg training params
  omega: 1.0
  kappa: 0.0
  t_min: 0.0
  t_max: 1.0

max_steps: ${training.max_steps}

clamp_utgt: 4.0
