defaults:
  - base.yaml
  - _self_

name: imagenet
data_type: image
label_shape: [1000]
src: ${env.folder_datasets_path}/imagenet/train/
src_val: ${env.folder_datasets_path}/imagenet/val/
s3_listdir_cache_dir: ~
local_dir: ~
metadata_ext: .meta.json
replace_broken_samples_with_random: false
