defaults:
  - env: local
  - model: dit_temf_ldm
  - loss: temf
  - training: base
  - sampling: recflow
  - dataset: imagenet
  - infra.yaml # TODO: merge with env?
  - pre_extract_latents: none # Some config for latents pre-extraction before training.

  - _self_ # (needed for Hydra 1.1 to avoid warnings)

batch_size: ~
detector_batch_gpu: ~
save_partial_stats_freq: ~
model_kwargs: {}
verbose: true
